#!/usr/bin/env bash
#A script that prints details about the domain and subdomain names

show_details()
{
    domain="$1"
    subdomain="$2"

    dig "$subdomain.$domain" | awk '/ANSWER SECTION:/{getline; printf "The subdomain %s is a %s record and points to %s\n", var, $4, $5}' var="$subdomain"

}

for subdomain in "www" "lb-01" "web-01" "web-02"
do

    if [ -z "$2" ] || [ "$2" == "$subdomain" ]; then
        show_details "$1" "$subdomain"
    fi

done
